[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"  # (or the latest LTS version you're using)

[[plugins]]
  package = "@netlify/plugin-cache"

  [plugins.inputs]
  paths = [".vite", "node_modules"]
